//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GostMVC.RezervacijeCRUDServis {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RezervacijeCRUDServis.IRezervacijeCRUDService")]
    public interface IRezervacijeCRUDService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRezervacijeCRUDService/dohvatiNepotvrdeneRezervacije", ReplyAction="http://tempuri.org/IRezervacijeCRUDService/dohvatiNepotvrdeneRezervacijeResponse")]
        ApartmaniService.DTO.RezervacijaDTO[] dohvatiNepotvrdeneRezervacije();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRezervacijeCRUDService/dohvatiNepotvrdeneRezervacije", ReplyAction="http://tempuri.org/IRezervacijeCRUDService/dohvatiNepotvrdeneRezervacijeResponse")]
        System.Threading.Tasks.Task<ApartmaniService.DTO.RezervacijaDTO[]> dohvatiNepotvrdeneRezervacijeAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRezervacijeCRUDService/dohvatiRezervacijeZaApartman", ReplyAction="http://tempuri.org/IRezervacijeCRUDService/dohvatiRezervacijeZaApartmanResponse")]
        ApartmaniService.DTO.RezervacijaDTO[] dohvatiRezervacijeZaApartman(int apartmanID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRezervacijeCRUDService/dohvatiRezervacijeZaApartman", ReplyAction="http://tempuri.org/IRezervacijeCRUDService/dohvatiRezervacijeZaApartmanResponse")]
        System.Threading.Tasks.Task<ApartmaniService.DTO.RezervacijaDTO[]> dohvatiRezervacijeZaApartmanAsync(int apartmanID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRezervacijeCRUDService/dohvatiRezervacijeZaGosta", ReplyAction="http://tempuri.org/IRezervacijeCRUDService/dohvatiRezervacijeZaGostaResponse")]
        ApartmaniService.DTO.RezervacijaDTO[] dohvatiRezervacijeZaGosta(int gostID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRezervacijeCRUDService/dohvatiRezervacijeZaGosta", ReplyAction="http://tempuri.org/IRezervacijeCRUDService/dohvatiRezervacijeZaGostaResponse")]
        System.Threading.Tasks.Task<ApartmaniService.DTO.RezervacijaDTO[]> dohvatiRezervacijeZaGostaAsync(int gostID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRezervacijeCRUDService/kreirajNovuRezervaciju", ReplyAction="http://tempuri.org/IRezervacijeCRUDService/kreirajNovuRezervacijuResponse")]
        bool kreirajNovuRezervaciju(ApartmaniService.DTO.RezervacijaDTO novaRezervacija);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRezervacijeCRUDService/kreirajNovuRezervaciju", ReplyAction="http://tempuri.org/IRezervacijeCRUDService/kreirajNovuRezervacijuResponse")]
        System.Threading.Tasks.Task<bool> kreirajNovuRezervacijuAsync(ApartmaniService.DTO.RezervacijaDTO novaRezervacija);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRezervacijeCRUDService/promijeniStatusRezervacije", ReplyAction="http://tempuri.org/IRezervacijeCRUDService/promijeniStatusRezervacijeResponse")]
        bool promijeniStatusRezervacije(int rezervacijaID, int status);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRezervacijeCRUDService/promijeniStatusRezervacije", ReplyAction="http://tempuri.org/IRezervacijeCRUDService/promijeniStatusRezervacijeResponse")]
        System.Threading.Tasks.Task<bool> promijeniStatusRezervacijeAsync(int rezervacijaID, int status);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRezervacijeCRUDService/provjeriDostupnost", ReplyAction="http://tempuri.org/IRezervacijeCRUDService/provjeriDostupnostResponse")]
        bool provjeriDostupnost(ApartmaniService.DTO.RezervacijaDTO rezervacija);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRezervacijeCRUDService/provjeriDostupnost", ReplyAction="http://tempuri.org/IRezervacijeCRUDService/provjeriDostupnostResponse")]
        System.Threading.Tasks.Task<bool> provjeriDostupnostAsync(ApartmaniService.DTO.RezervacijaDTO rezervacija);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRezervacijeCRUDService/otkaziRezervaciju", ReplyAction="http://tempuri.org/IRezervacijeCRUDService/otkaziRezervacijuResponse")]
        bool otkaziRezervaciju(int rezervacijaID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRezervacijeCRUDService/otkaziRezervaciju", ReplyAction="http://tempuri.org/IRezervacijeCRUDService/otkaziRezervacijuResponse")]
        System.Threading.Tasks.Task<bool> otkaziRezervacijuAsync(int rezervacijaID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRezervacijeCRUDServiceChannel : GostMVC.RezervacijeCRUDServis.IRezervacijeCRUDService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RezervacijeCRUDServiceClient : System.ServiceModel.ClientBase<GostMVC.RezervacijeCRUDServis.IRezervacijeCRUDService>, GostMVC.RezervacijeCRUDServis.IRezervacijeCRUDService {
        
        public RezervacijeCRUDServiceClient() {
        }
        
        public RezervacijeCRUDServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RezervacijeCRUDServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RezervacijeCRUDServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RezervacijeCRUDServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ApartmaniService.DTO.RezervacijaDTO[] dohvatiNepotvrdeneRezervacije() {
            return base.Channel.dohvatiNepotvrdeneRezervacije();
        }
        
        public System.Threading.Tasks.Task<ApartmaniService.DTO.RezervacijaDTO[]> dohvatiNepotvrdeneRezervacijeAsync() {
            return base.Channel.dohvatiNepotvrdeneRezervacijeAsync();
        }
        
        public ApartmaniService.DTO.RezervacijaDTO[] dohvatiRezervacijeZaApartman(int apartmanID) {
            return base.Channel.dohvatiRezervacijeZaApartman(apartmanID);
        }
        
        public System.Threading.Tasks.Task<ApartmaniService.DTO.RezervacijaDTO[]> dohvatiRezervacijeZaApartmanAsync(int apartmanID) {
            return base.Channel.dohvatiRezervacijeZaApartmanAsync(apartmanID);
        }
        
        public ApartmaniService.DTO.RezervacijaDTO[] dohvatiRezervacijeZaGosta(int gostID) {
            return base.Channel.dohvatiRezervacijeZaGosta(gostID);
        }
        
        public System.Threading.Tasks.Task<ApartmaniService.DTO.RezervacijaDTO[]> dohvatiRezervacijeZaGostaAsync(int gostID) {
            return base.Channel.dohvatiRezervacijeZaGostaAsync(gostID);
        }
        
        public bool kreirajNovuRezervaciju(ApartmaniService.DTO.RezervacijaDTO novaRezervacija) {
            return base.Channel.kreirajNovuRezervaciju(novaRezervacija);
        }
        
        public System.Threading.Tasks.Task<bool> kreirajNovuRezervacijuAsync(ApartmaniService.DTO.RezervacijaDTO novaRezervacija) {
            return base.Channel.kreirajNovuRezervacijuAsync(novaRezervacija);
        }
        
        public bool promijeniStatusRezervacije(int rezervacijaID, int status) {
            return base.Channel.promijeniStatusRezervacije(rezervacijaID, status);
        }
        
        public System.Threading.Tasks.Task<bool> promijeniStatusRezervacijeAsync(int rezervacijaID, int status) {
            return base.Channel.promijeniStatusRezervacijeAsync(rezervacijaID, status);
        }
        
        public bool provjeriDostupnost(ApartmaniService.DTO.RezervacijaDTO rezervacija) {
            return base.Channel.provjeriDostupnost(rezervacija);
        }
        
        public System.Threading.Tasks.Task<bool> provjeriDostupnostAsync(ApartmaniService.DTO.RezervacijaDTO rezervacija) {
            return base.Channel.provjeriDostupnostAsync(rezervacija);
        }
        
        public bool otkaziRezervaciju(int rezervacijaID) {
            return base.Channel.otkaziRezervaciju(rezervacijaID);
        }
        
        public System.Threading.Tasks.Task<bool> otkaziRezervacijuAsync(int rezervacijaID) {
            return base.Channel.otkaziRezervacijuAsync(rezervacijaID);
        }
    }
}
