//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApartmaniService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Apartman
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Apartman()
        {
            this.Rezervacija = new HashSet<Rezervacija>();
        }
    
        public int ApartmanID { get; set; }
        public string Naziv { get; set; }
        public string BrojOsoba { get; set; }
        public string Adresa { get; set; }
        public string Grad { get; set; }
        public int Povrsina { get; set; }
        public decimal Cijena { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rezervacija> Rezervacija { get; set; }
    }
}
