//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApartmaniService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rezervacija
    {
        public int RezervacijaID { get; set; }
        public int GostID { get; set; }
        public int ApartmanID { get; set; }
        public System.DateTime Od { get; set; }
        public System.DateTime Do { get; set; }
        public short Status { get; set; }
    
        public virtual Apartman Apartman { get; set; }
        public virtual Gost Gost { get; set; }
    }
}
